In [4]:
import numpy as np

In [126]:
#1. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
n1 = np.array([1,7,13,105])
print(f"Size of memory occupied by array = {n1.nbytes}")

Size of memory occupied by array = 32


In [9]:
#2. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
n1 = np.array([5, 6, 8, 2, 1, 9])
n2 = np.array([6, 7, 2, 0, 1, 10])
print(f"n1 elements > n2 elements {n1>n2}")
print(f"n1 elements >= n2 elements {n1>=n2}")
print(f"n1 elements < n2 elements {n1<n2}")
print(f"n1 elements <= n2 elements {n1<=n2}")

n1 elements > n2 elements [False False  True  True False False]
n1 elements >= n2 elements [False False  True  True  True False]
n1 elements < n2 elements [ True  True False False False  True]
n1 elements <= n2 elements [ True  True False False  True  True]


In [15]:
#3.  Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.
arr1 = np.zeros(10, dtype=np.int8)
print(arr1)
arr2 = np.ones(10, dtype=np.int8)
print(arr2)
arr3 = np.ones(10, dtype=np.int8) * 5
print(arr3)
arr4 = np.ones(10, dtype=np.int8) * 10
print(arr4)
arr5 = np.ones(10, dtype=np.int8) *20
print(arr5)
arr6 = np.ones(10, dtype=np.int8) * 50
print(arr6)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]
[10 10 10 10 10 10 10 10 10 10]
[20 20 20 20 20 20 20 20 20 20]
[50 50 50 50 50 50 50 50 50 50]


In [19]:
#4. Write a NumPy program to create an array of integers from 30 to 70.
arr1 = np.arange(30, 71)
print(arr1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [21]:
#5. Write a NumPy program to create an array of integers from 50 to 95.
arr1 = np.arange(50, 96)
print(arr1)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [22]:
#6. Write a NumPy program to create an array of all even integers from 20 to 80.
arr1 = np.arange(20, 81, 2)
print(arr1)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [26]:
#7.Write a NumPy program to create an array of all odd integers from 20 to 80.
arr1 = np.arange(21, 80, 2)
print(arr1)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [28]:
#8. Write a NumPy program to generate an array of 15 random numbers from 10    to 40.
arr = np.random.randint(10, 40, 15)
print(arr)

[32 37 37 34 16 25 14 24 28 15 17 37 24 16 19]


In [127]:
#9. Write a NumPy program to generate an array of 10 random numbers from 30    to 50.
arr = np.random.randint(30, 50, 10)
print(arr)

[40 42 30 47 44 34 46 32 36 38]


In [128]:
#10. Write a NumPy program to generate an array of 20 random numbers from 50    to 90.
arr = np.random.randint(50, 90, 20)
print(arr)

[67 86 84 67 89 86 79 61 63 66 76 66 83 53 83 76 72 67 67 50]


In [33]:
#11. Create any two arrays & perform various mathematical operations. 
#i.e. Addition, Substraction, Multiplication, Divide.
n1 = np.array([6, 12, 8, 8, 9, 14])
n2 = np.array([2, 2, 2, 4, 3, 7])
print(f"Addition = {n1+n2}")
print(f"Subustraction = {n1-n2}")
print(f"Multiplication = {n1*n2}")
print(f"Divide = {n1/n2}")

Addition = [ 8 14 10 12 12 21]
Subustraction = [ 4 10  6  4  6  7]
Multiplication = [12 24 16 32 27 98]
Divide = [3. 6. 4. 2. 3. 2.]


In [38]:
#12. Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.
arr1 = np.arange(10, 22)
arr1 = arr1.reshape([3,4])
print(arr1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [132]:
#13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, 
#the rest are 0.
#arr1 = np.array([1,0,0,0,1,0,0,0,1])
#arr1 = arr1.reshape([3, 3])
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
#14. Write a NumPy program to find the number of rows and columns in a given matrix.
arr1 = np.array([1,0,0,0,1,0,0,0,1])
arr1 = arr1.reshape([3, 3])
print(f"Number of rows and columns in array: {arr1.shape}")

Number of rows and columns in array: (3, 3)


In [135]:
#15. Write a NumPy program to create a 5x5 zero matrix with elements on the     
#main diagonal equal to 1, 2, 3, 4, 5.
# arr1 = np.zeros(25,dtype=np.int8)
# arr1 = arr1.reshape([5, 5])
# arr1[0][0] = 1
# arr1[1][1] = 2
# arr1[2][2] = 3
# arr1[3][3] = 4
# arr1[4][4] = 5
# print(arr1)
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [65]:
#16. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.62552742 0.73291389 0.68727623]
  [0.43169323 0.43170845 0.72420588]
  [0.74112199 0.55639551 0.21538234]]

 [[0.47894433 0.16337811 0.10155244]
  [0.53469867 0.01259359 0.11603195]
  [0.16285104 0.61995741 0.7475283 ]]

 [[0.10294675 0.25428596 0.2882824 ]
  [0.6310799  0.22150412 0.32881278]
  [0.68399579 0.92986167 0.78381497]]]


In [81]:
#17. Write a NumPy program to create a 2x3x4 array filled with arbitrary values.
arr = np.random.random((2, 3, 4))
print(arr)

[[[0.33508069 0.99657729 0.88589994 0.5563732 ]
  [0.97502877 0.69893154 0.69950518 0.30539302]
  [0.02729229 0.05206724 0.64379858 0.17708804]]

 [[0.56301097 0.21953131 0.76447078 0.68020703]
  [0.1070244  0.73999214 0.22866914 0.77216851]
  [0.16743142 0.88540461 0.72378836 0.86033471]]]


In [114]:
#18. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.
l1 = [1, 2, 3, 4, 5, 6, 7, 8]
print(f"List: {l1}")
print(f"Type: {type(l1)}")
arr = np.array(l1)
print(f"array: {arr}")
print(f"Type: {type(arr)}")

List: [1, 2, 3, 4, 5, 6, 7, 8]
Type: <class 'list'>
array: [1 2 3 4 5 6 7 8]
Type: <class 'numpy.ndarray'>


In [88]:
#19. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
arr = np.arange(2, 11)
arr = arr.reshape([3, 3])
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [136]:
#20. Write a NumPy program to create an array with values ranging from 12 to 38.
arr = np.arange(12, 38)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [93]:
#21. Write a NumPy program to reverse an array (the first element becomes the last).
arr = np.arange(10)
print(f"Original array: {arr}")
arr = arr[::-1]
print(f"Reverse array: {arr}")

Original array: [0 1 2 3 4 5 6 7 8 9]
Reverse array: [9 8 7 6 5 4 3 2 1 0]


In [110]:
#22. Write a NumPy program to convert an data type into to a floating type.
arr = np.arange(10)
print(arr)
print(f"Type = {arr.dtype}")
arr = arr.astype('float64')
print(arr)
print(f"Type = {arr.dtype}")

[0 1 2 3 4 5 6 7 8 9]
Type = int64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Type = float64


In [115]:
#23. Write a NumPy program to convert a list array.
l1 = [1, 2, 3, 4, 5, 6, 7, 8]
print(f"List: {l1}")
print(f"Type: {type(l1)}")
arr = np.array(l1)
print(f"array: {arr}")
print(f"Type: {type(arr)}")

List: [1, 2, 3, 4, 5, 6, 7, 8]
Type: <class 'list'>
array: [1 2 3 4 5 6 7 8]
Type: <class 'numpy.ndarray'>


In [121]:
#24. Write a NumPy program to get the element-wise remainder of an array of division.
arr = np.arange(10)
print(f"Original array: {arr}")

print(f"Reminder of an array of division: {np.remainder(arr, 2)}")

Original array: [0 1 2 3 4 5 6 7 8 9]
Reminder of an array of division: [0 1 0 1 0 1 0 1 0 1]


In [123]:
#25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are 
#divisible by 3.
arr = np.arange(20, 50)
print(f"Original array: {arr}")

print(f"Reminder of an array of division: {np.remainder(arr, 3)}")

Original array: [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
Reminder of an array of division: [2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
